2022-06-03/11:29:32		Exception occured Failed during training in module [__main__] class [ClientApp] method[train_func] Python script name [main.py] line number [204] error message [module 'json' has no attribute 'jump'] 
2022-06-03/11:33:59		Exception occured Failed during training in module [__main__] class [ClientApp] method[train_func] Python script name [main.py] line number [204] error message [module 'json' has no attribute 'jump'] 
2022-06-03/12:45:35		Exception occured Failed during training in module [cv_image_suit.utils.normal_utils.model] class [modell] method[get_model] Python script name [model.py] line number [48] error message [SavedModel file does not exist at: G:\Ineuron\DLCVNLP\cv\cv_image_suit\cv_image_suit/Checkpoint/Model_ckpt.h5/{saved_model.pbtxt|saved_model.pb}] 
2022-06-03/12:45:35		Exception occured Failed during training in module [cv_image_suit.utils.normal_utils.model] class [modell] method[get_model] Python script name [model.py] line number [180] error message [Failed during training in module [cv_image_suit.utils.normal_utils.model] class [modell] method[get_model] Python script name [model.py] line number [48] error message [SavedModel file does not exist at: G:\Ineuron\DLCVNLP\cv\cv_image_suit\cv_image_suit/Checkpoint/Model_ckpt.h5/{saved_model.pbtxt|saved_model.pb}]] 
2022-06-03/12:45:35		Exception occured Failed during training in module [__main__] class [ClientApp] method[train_func] Python script name [main.py] line number [214] error message [[Errno 2] No such file or directory: 'Logs/logs.txt']
